"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-23 23:50:30.279792
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('razorpay_key_id', sa.Text(), nullable=True),
    sa.Column('razorpay_key_secret_enc', sa.Text(), nullable=True),
    sa.Column('razorpay_webhook_secret_enc', sa.Text(), nullable=True),
    sa.Column('contact_hour_start', sa.SmallInteger(), server_default=sa.text('8'), nullable=False),
    sa.Column('contact_hour_end', sa.SmallInteger(), server_default=sa.text('19'), nullable=False),
    sa.Column('weekly_touch_cap', sa.SmallInteger(), server_default=sa.text('2'), nullable=False),
    sa.Column('lifetime_touch_cap', sa.SmallInteger(), server_default=sa.text('6'), nullable=False),
    sa.Column('approval_value_threshold_paise', sa.BigInteger(), server_default=sa.text('50000000'), nullable=False),
    sa.Column('approval_tone_tier', sa.SmallInteger(), server_default=sa.text('3'), nullable=False),
    sa.Column('is_paused', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('razorpay_event_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_dedupe', 'webhook_events', ['razorpay_event_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('gate_verdicts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.Text(), nullable=False),
    sa.Column('entry_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor IN ('agent', 'human', 'system', 'counterparty')", name='ck_audit_log_actor'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counterparties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_normalized', sa.Text(), nullable=False),
    sa.Column('gstin', sa.Text(), nullable=True),
    sa.Column('is_msme', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('preferred_language', sa.Text(), server_default=sa.text("'en'"), nullable=False),
    sa.Column('lifetime_revenue_paise', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_days_to_pay', sa.Numeric(), nullable=True),
    sa.Column('broken_promise_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_quarantined', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'gstin', name='uq_counterparty_gstin')
    )
    op.create_index('idx_cp_match', 'counterparties', ['merchant_id', 'name_normalized'], unique=False)
    op.create_table('metrics_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_outstanding_paise', sa.BigInteger(), nullable=False),
    sa.Column('recovered_paise', sa.BigInteger(), nullable=False),
    sa.Column('dso_days', sa.Numeric(), nullable=False),
    sa.Column('recovery_rate', sa.Numeric(), nullable=False),
    sa.Column('promise_kept_rate', sa.Numeric(), nullable=False),
    sa.Column('invoices_by_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'snapshot_date', name='uq_metrics_snapshot_date')
    )
    op.create_table('consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('is_permitted', sa.Boolean(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opt_out_token', sa.Text(), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'sms', 'whatsapp')", name='ck_consents_channel'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('counterparty_id', 'channel', name='uq_consent_channel')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.Text(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('outstanding_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('terms_days', sa.SmallInteger(), nullable=False),
    sa.Column('po_ref', sa.Text(), nullable=True),
    sa.Column('has_gst', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('payment_status', sa.String(length=32), server_default=sa.text("'unpaid'"), nullable=False),
    sa.Column('recovery_state', sa.String(length=32), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('inferred_cause', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('days_past_due', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('aging_bucket', sa.Text(), nullable=True),
    sa.Column('crosses_msme_45', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('collectability_score', sa.Numeric(), nullable=True),
    sa.Column('priority_score', sa.Numeric(), nullable=True),
    sa.Column('priority_reason', sa.Text(), nullable=True),
    sa.Column('touch_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_tone_tier', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("inferred_cause IN ('oversight', 'cash_crunch', 'dispute', 'wrong_contact', 'awaiting_docs', 'refusal', 'unknown')", name='ck_invoices_inferred_cause'),
    sa.CheckConstraint("payment_status IN ('unpaid', 'partially_paid', 'paid', 'written_off')", name='ck_invoices_payment_status'),
    sa.CheckConstraint("recovery_state IN ('not_started', 'nudged', 'chasing', 'promised', 'broken_promise', 'escalated', 'human_review', 'stopped', 'settled')", name='ck_invoices_recovery_state'),
    sa.CheckConstraint("stop_reason IN ('settled', 'disputed', 'opted_out', 'broken_promises_exceeded', 'touch_cap_reached', 'no_consent', 'merchant_excluded', 'written_off')", name='ck_invoices_stop_reason'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_number', 'invoices', ['merchant_id', 'invoice_number'], unique=True)
    op.create_index('idx_worklist', 'invoices', ['merchant_id', 'recovery_state', sa.literal_column('priority_score DESC')], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('tone_tier', sa.SmallInteger(), nullable=True),
    sa.Column('proposed_by', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('gate_verdicts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('gate_failure_reason', sa.Text(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'sms', 'whatsapp')", name='ck_actions_channel'),
    sa.CheckConstraint("proposed_by IN ('agent', 'human', 'system', 'counterparty')", name='ck_actions_proposed_by'),
    sa.CheckConstraint("status IN ('proposed', 'gated_pass', 'gated_fail', 'awaiting_approval', 'executed', 'failed', 'revoked')", name='ck_actions_status'),
    sa.CheckConstraint("type IN ('create_payment_link', 'send_message', 'log_promise', 'offer_installment', 'switch_channel', 'escalate_tier', 'snooze', 'mark_disputed', 'stop')", name='ck_actions_type'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    # fk_actions_message_id (message_id -> messages.id) is added at the end of upgrade(),
    # after messages exists, to break the actions<->messages cycle.
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_actions_invoice', 'actions', ['invoice_id'], unique=False)
    op.create_index('idx_dispatch', 'actions', ['merchant_id', 'status', 'scheduled_for'], unique=False)
    op.create_table('payment_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('razorpay_link_id', sa.Text(), nullable=False),
    sa.Column('short_url', sa.Text(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('reference_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('expire_by', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accept_partial', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_payment_link_idempotency')
    )
    op.create_table('replies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('extracted_date', sa.Date(), nullable=True),
    sa.Column('routed_to_human', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'sms', 'whatsapp')", name='ck_replies_channel'),
    sa.CheckConstraint("intent IN ('dispute', 'promise_to_pay', 'query', 'refusal', 'wrong_contact', 'acknowledgment', 'unclear')", name='ck_replies_intent'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('tone_tier', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('delivery_status', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'sms', 'whatsapp')", name='ck_messages_channel'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('reply_id', sa.Uuid(), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=False),
    sa.Column('promised_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # actions.message_id <-> messages.action_id is a cycle; the message_id FK is added here,
    # after messages exists, because an inline use_alter FK is skipped by CREATE TABLE.
    op.create_foreign_key(
        "fk_actions_message_id", "actions", "messages", ["message_id"], ["id"]
    )

    # audit_log is append-only. No UPDATE, no DELETE — enforced by PostgreSQL RULEs so the
    # compliance guarantee holds at the database, not by application convention.
    op.execute("CREATE RULE audit_log_no_update AS ON UPDATE TO audit_log DO INSTEAD NOTHING")
    op.execute("CREATE RULE audit_log_no_delete AS ON DELETE TO audit_log DO INSTEAD NOTHING")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP RULE IF EXISTS audit_log_no_delete ON audit_log")
    op.execute("DROP RULE IF EXISTS audit_log_no_update ON audit_log")
    op.drop_constraint("fk_actions_message_id", "actions", type_="foreignkey")
    op.drop_table('promises')
    op.drop_table('messages')
    op.drop_table('replies')
    op.drop_table('payment_links')
    op.drop_index('idx_dispatch', table_name='actions')
    op.drop_index('idx_actions_invoice', table_name='actions')
    op.drop_table('actions')
    op.drop_index('idx_worklist', table_name='invoices')
    op.drop_index('idx_invoice_number', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('contacts')
    op.drop_table('consents')
    op.drop_table('metrics_snapshots')
    op.drop_index('idx_cp_match', table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_table('audit_log')
    op.drop_index('idx_webhook_dedupe', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('merchants')
    # ### end Alembic commands ###
